### ISSUE TITLE
domain_name not given or empty

### ISSUE THREAD

**Issue by huziahmetovsv** [flant/clusterissuer-regru#12]
Hi. Tryed to issue wildcard certificate with manifest:
```
- apiVersion: cert-manager.io/v1
      kind: Certificate
      metadata:
        name: wildcard-infra-example-com
      spec:
        secretName: wildcard-infra-example-com-secret
        issuerRef:
          name: regru-dns
          kind: ClusterIssuer
        dnsNames:
          - *.infra.example.com
```
But in pod log see url:
api.reg.ru/api/regru2/zone/add_txt?input_data=%7B%22username%22%3A%22my_regru_user%22%2C%22password%22%3A%22smy_regru_password%22%2C%22domains%22%3A%5B%7B%22**dname%22%3A%22%22%7D%5D%2C%22subdomain%22%3A%22_acme-challenge.infra.example.com**.%22%2C%22text%22%3A%22CIFuiEULSPsSYQIemqFM0-dAreebSWy-LdWUw_QoMzw%22%2C%22output_content_type%22%3A%22plain%22%7D&input_format=json

And error responce from api:
```
{
   "answer" : {
      "domains" : [
         {
            "error_code" : "NO_DOMAIN",
            "error_text" : "domain_name not given or empty",
            "result" : "error"
         }
      ]
   },
   "charset" : "utf-8",
   "messagestore" : null,
   "result" : "success"
}
```
As i understand, from api docs, my url format whong, it shoul be
api.reg.ru/api/regru2/zone/add_txt?input_data=%7B%22username%22%3A%22test%22%2C%22password%22%3A%22test%22%2C%22domains%22%3A%5B%7B%22dname%22%3A%22test.ru%22%7D%2C%7B%22**dname%22%3A%22test.com%22%7D%5D%2C%22subdomain%22%3A%22mail**%22%2C%22text%22%3A%22testmail%22%2C%22output_content_type%22%3A%22plain%22%7D&input_format=json
